services:
  
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mosque-frontend
    restart: always
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portal.rule=Host(`portal.ccai-stjean.org`)"
      - "traefik.http.routers.portal.entrypoints=websecure"
      - "traefik.http.routers.portal.tls=true"
      - "traefik.http.services.portal.loadbalancer.server.port=3000"
